FROM node:20-bookworm

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm rebuild

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]